version: '3.9'

services:
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
    - 5332:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: {}